### ISSUE TITLE
[BUG] Exported COMBINE archives do not contain all files required for simulation

### ISSUE THREAD

**Issue by jonrkarr** [PMR2/pmr2.omex#10]
Files imported into CellML files are sometimes missing from the exported COMBINE archives (e.g., https://models.physiomeproject.org/e/440/download_generated_omex). COMBINE archives can't be simulated without these files. These files appear to be present in the Git repositories and exported tar.gz files.

Examples of missing files:
- `e/43f`
  - `/components/default-variable-values.xml`
  - `/components/IK.xml`
  - `/components/Ileak.xml`
  - `/components/INa.xml`
  - `/components/units.xml`
  - `/experiments/periodic-IStim-protocol.xml`
  - `/experiments/time.xml`
- `e/49f`
  - `/cell_model_interface.xml`
  - `/default_variable_values.xml`
  - `/units_model.xml`
- `e/440`
  - `/components/default-variable-values.xml`
  - `/components/IK.xml`
  - `/components/Ileak.xml`
  - `/components/INa.xml`
  - `/components/units.xml`
  - `/experiments/periodic-IStim-protocol.xml`
  - `/experiments/time.xml`

**Comment by jonrkarr** [comment]
@nickerso this the issue I mentioned today (2021-12-21). The origin appears to be the method for exporting COMBINE archives.

**Comment by metatoaster** [comment]
This is solely caused by the resolution of imports of CellML file being done only on files with the `.cellml` filename extension.  While it is possible to search for any supported imports (i.e. SED-ML and CellML) if given an `.xml` filename extension, I feel this is currently unnecessary and somewhat impractical given that we want to enforce community supported standard of naming of model files.

Would appreciate some input from @nickerso

**Comment by jonrkarr** [comment]
Ignoring this is resulting in producing broken COMBINE archives without users receiving clear notification that the archives are not expected to be functional. I think users will likely perceive this as a bug in PMR. This furthers the confusion around COMBINE archives and SED-ML.

If PMR doesn't intend to properly resolve imports, here's two alternative paths that I think would largely address the issue:
- Clearly communicate errors
  - Do not display COMBINE archive export buttons for affected projects
  - Instead, display a message that indicates that the project cannot be exported to a COMBINE archive
- OR automatically clean up archives
  - Automatically normalize file extensions
  - Then correctly resolve imported files

**Comment by metatoaster** [comment]
@jonrkarr The software intend to produce correct archives, but that needs to run in conjunction with valid and supported data being published.  We appreciate your effort in reviewing peer-reviewing our efforts here, so let's not jump to conclusions too hastily.

**Comment by metatoaster** [comment]
I am expiring the exposure given that the title clearly state that this was a test.

**Comment by jonrkarr** [comment]
Expiring the affected exposures (exposure with files missing from exported COMBINE archives) seems like a good solution.

Will all such affected exposures be expired?

**Comment by metatoaster** [comment]
Yes, provided that they are reported.  For real exposures we will have a reviewer rename the files and create a brand new exposure as the underlying model files provided at each link are intended to be immutable.

Do note that all features (broken or not) will still remain active in expired exposures, but given the warning users are at least given a warning of this state.
