### ISSUE TITLE
Update license to MIT or other permissive licence

### ISSUE THREAD

**Issue by bilalshaikh42** [PMR2/pmr2.omex#9]
The docs folder contains a file indicating that the repo is under the GPL 3 license. Would it be license this repository under MIT or a more permissive license so we can incorporate some of it into the code to import PMR models into BioSimulations?

**Comment by metatoaster** [comment]
The license is currently under GPL2; a more permissive license like MIT allows free-for-all commercialization (especially in having their own private closed sourced forks without contribution back to original authors) by any third-party without the consent of the authors, which is a rather detrimental decision to make as this would result in a loss of opportunity in capturing value.  I strongly suggest that applying a dual-licensing regime which would then allow proprietary software to pay an appropriate cost for closed-source usage of the code, however in this particular case, I don't see why we can re-license some of the relevant code that are being copied to BioSimulations. 

Moreover, Plone is licensed under the GPL, and this package directly links to it.

**Comment by bilalshaikh42** [comment]
I see, I wasn't sure how the code was linked to plone. Can this repository be run independently of the entire infrastructure? If so, that would be something quite useful for us. However, if it's only possible as a plugin, then we probably won't be able to directly use the code anyway

**Comment by metatoaster** [comment]
> Can this repository be run independently of the entire infrastructure?

No, aside from a few utility functions (such as creation of zip files and the like), much of the code here depends directly on the Zope/Plone architecture either directly or indirectly through `pmr2.app`, so it's definitely better to refer to the implementation and take the concepts and build your own.

**Comment by bilalshaikh42** [comment]
Got it. Thanks for the info.
